spring.application.name=kaashiv
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databasename=Student_Api;trustservercertificate=true
spring.datasource.username=surya
spring.datasource.password=123
spring.jpa.show-sql=true